import type { Topic, BookData, MatchData, University, Track } from './types';

export const TOPIC_DB: Record<Track, Topic[]> = {
  공학: [
    {
      subj: '과학',
      sub: '화학Ⅰ · 산화환원',
      title: '전기차 배터리 양극재 변천사로 본 산화환원 반응의 응용',
      desc: 'LCO, NCM, LFP 등 양극재의 진화 과정을 산화환원 전위와 연결하여 분석. 화학공학·신소재공학 학과에 강력 어필.',
      diff: '중상',
      uniq: 92,
      fit: 96,
      featured: true,
    },
    {
      subj: '수학',
      sub: '미적분 · 응용',
      title: 'AI 자율주행차 경로 최적화 알고리즘에서 미분의 활용',
      desc: '자율주행 차량의 실시간 경로 결정에 사용되는 변분법과 그래디언트 디센트를 미적분 개념과 연결.',
      diff: '상',
      uniq: 88,
      fit: 91,
      featured: false,
    },
    {
      subj: '과학',
      sub: '물리학Ⅰ · 역학',
      title: '드론 안정 비행을 위한 PID 제어와 뉴턴의 운동법칙',
      desc: '드론 제어 알고리즘 속에서 작용하는 운동법칙을 직접 분석하고 시뮬레이션.',
      diff: '중',
      uniq: 84,
      fit: 89,
      featured: false,
    },
    {
      subj: '사회',
      sub: '통합사회 · 기술',
      title: '반도체 산업의 지정학과 한국 기업의 대응 전략',
      desc: 'TSMC, 삼성, SK하이닉스의 글로벌 경쟁 구도와 미·중 갈등이 산업에 미치는 영향 분석.',
      diff: '중',
      uniq: 80,
      fit: 85,
      featured: false,
    },
  ],
  자연과학: [
    {
      subj: '과학',
      sub: '생명과학Ⅰ · 유전',
      title: 'CRISPR-Cas9 유전자 편집 기술의 작동 원리와 윤리 쟁점',
      desc: '최근 노벨화학상 수상 기술의 분자생물학적 메커니즘과 인류 적용 시 고려사항.',
      diff: '상',
      uniq: 94,
      fit: 97,
      featured: true,
    },
    {
      subj: '과학',
      sub: '화학Ⅰ · 화학결합',
      title: '의약품 분자구조 속 수소결합이 약효 지속시간에 미치는 영향',
      desc: '아세트아미노펜·이부프로펜의 분자구조 비교 분석.',
      diff: '중',
      uniq: 84,
      fit: 89,
      featured: false,
    },
    {
      subj: '과학',
      sub: '지구과학Ⅰ · 기후',
      title: '엘니뇨와 라니냐의 메커니즘이 한반도 농업에 미치는 영향',
      desc: '해수면 온도 변화가 농작물 수확량에 미치는 영향을 데이터로 분석.',
      diff: '중상',
      uniq: 86,
      fit: 88,
      featured: false,
    },
    {
      subj: '수학',
      sub: '확률과 통계',
      title: '몬테카를로 시뮬레이션으로 본 π 값의 추정 정확도',
      desc: '난수와 확률을 이용한 수치해석 기법을 직접 코딩하여 검증.',
      diff: '중',
      uniq: 82,
      fit: 85,
      featured: false,
    },
  ],
  의약: [
    {
      subj: '과학',
      sub: '생명과학Ⅰ · 면역',
      title: 'mRNA 백신의 작동 원리와 차세대 감염병 대응 전략',
      desc: '코로나19 백신을 통해 본 면역학·분자생물학의 융합 연구.',
      diff: '상',
      uniq: 95,
      fit: 98,
      featured: true,
    },
    {
      subj: '과학',
      sub: '화학Ⅰ · 동적평형',
      title: '혈액 pH 항상성 메커니즘에서 본 르샤틀리에 원리',
      desc: '호흡성·대사성 산증을 화학평형으로 해석.',
      diff: '중',
      uniq: 76,
      fit: 91,
      featured: false,
    },
    {
      subj: '사회',
      sub: '윤리와 사상',
      title: '안락사 합법화 논쟁에서 의료윤리의 4원칙 적용',
      desc: '자율성, 선행, 무해, 정의 원칙을 실제 사례에 적용.',
      diff: '중',
      uniq: 82,
      fit: 87,
      featured: false,
    },
    {
      subj: '과학',
      sub: '생명과학Ⅰ · 생태',
      title: '항생제 내성균의 진화와 다제내성 슈퍼박테리아 대응',
      desc: '진화론적 관점에서 본 미생물의 적응 메커니즘 분석.',
      diff: '중상',
      uniq: 89,
      fit: 93,
      featured: false,
    },
  ],
  경상: [
    {
      subj: '사회',
      sub: '경제 · 시장',
      title: '인플레이션 시대의 가격탄력성과 소비자 행동 변화',
      desc: '식료품·생필품 카테고리별 수요탄력성 차이를 데이터로 분석.',
      diff: '중',
      uniq: 85,
      fit: 95,
      featured: true,
    },
    {
      subj: '수학',
      sub: '확률과 통계',
      title: '몬테카를로 시뮬레이션을 활용한 주식 포트폴리오 리스크 분석',
      desc: '확률분포와 정규분포를 이용한 자산 배분 전략.',
      diff: '상',
      uniq: 90,
      fit: 92,
      featured: false,
    },
    {
      subj: '사회',
      sub: '경제 · 행동경제',
      title: '넛지 이론으로 본 금융상품 마케팅의 윤리적 경계',
      desc: '리처드 탈러의 행동경제학을 한국 금융시장에 적용.',
      diff: '중',
      uniq: 84,
      fit: 89,
      featured: false,
    },
    {
      subj: '영어',
      sub: '영어Ⅰ',
      title: 'ESG 경영이 글로벌 기업 평가에 미치는 영향 (영자 기사 분석)',
      desc: 'Financial Times·WSJ 기사 비교를 통한 영어 독해 + 경영 분석.',
      diff: '중',
      uniq: 78,
      fit: 86,
      featured: false,
    },
  ],
  사회과학: [
    {
      subj: '사회',
      sub: '정치와 법',
      title: '한국 선거제도(병립형 vs 연동형)의 정치적 효과 비교',
      desc: '2024 총선 결과 데이터를 기반으로 선거제도 효과 분석.',
      diff: '중상',
      uniq: 91,
      fit: 94,
      featured: true,
    },
    {
      subj: '국어',
      sub: '독서 · 사회',
      title: '미디어 프레이밍이 여론 형성에 미치는 영향 (신문 비교)',
      desc: '동일 사건에 대한 보수·진보 매체의 프레이밍 차이 분석.',
      diff: '중',
      uniq: 82,
      fit: 88,
      featured: false,
    },
    {
      subj: '사회',
      sub: '사회·문화',
      title: 'MZ세대의 직장 문화 변화와 조직심리학적 해석',
      desc: '세대 갈등 데이터를 사회학·심리학 관점에서 통합 분석.',
      diff: '중',
      uniq: 80,
      fit: 85,
      featured: false,
    },
    {
      subj: '영어',
      sub: '영어Ⅰ',
      title: 'Soft Power 개념으로 본 K-콘텐츠의 글로벌 확산 (영어 발표)',
      desc: '조지프 나이의 이론과 한류의 사례 연구.',
      diff: '중',
      uniq: 84,
      fit: 87,
      featured: false,
    },
  ],
  인문: [
    {
      subj: '국어',
      sub: '문학 · 현대시',
      title: '윤동주 시에 나타난 식민지 지식인의 자기 응시',
      desc: '"서시", "별 헤는 밤" 등을 자아 정체성 관점에서 재해석.',
      diff: '중',
      uniq: 86,
      fit: 95,
      featured: true,
    },
    {
      subj: '국어',
      sub: '독서 · 인문',
      title: '"총·균·쇠"로 본 환경결정론과 문명사관의 한계',
      desc: '재레드 다이아몬드의 주장에 대한 비판적 독해.',
      diff: '중상',
      uniq: 88,
      fit: 92,
      featured: false,
    },
    {
      subj: '사회',
      sub: '한국사',
      title: '실학사상에서 발견되는 근대성과 그 한계',
      desc: '정약용의 경세유표와 당대 정치 현실의 거리.',
      diff: '중',
      uniq: 80,
      fit: 86,
      featured: false,
    },
    {
      subj: '영어',
      sub: '영어 · 문학',
      title: '셰익스피어 햄릿에 나타난 르네상스 휴머니즘의 균열',
      desc: '원문 발췌 분석을 통한 영문학 + 인문학 융합.',
      diff: '상',
      uniq: 90,
      fit: 89,
      featured: false,
    },
  ],
  교육: [
    {
      subj: '사회',
      sub: '사회·문화',
      title: '에듀테크가 학습자 자기주도성에 미치는 영향',
      desc: '디지털 학습 도구 사용과 학업 동기의 상관관계 연구.',
      diff: '중',
      uniq: 83,
      fit: 96,
      featured: true,
    },
    {
      subj: '국어',
      sub: '독서·교육',
      title: '비고츠키의 근접발달영역(ZPD) 이론과 또래 학습',
      desc: '교육심리학 고전 이론의 현대 교실 적용 사례.',
      diff: '중',
      uniq: 80,
      fit: 92,
      featured: false,
    },
    {
      subj: '사회',
      sub: '윤리와 사상',
      title: '루소 "에밀"에서 본 자연주의 교육관의 현재성',
      desc: '루소의 교육철학을 한국 교육 현실에 비추어 분석.',
      diff: '중',
      uniq: 85,
      fit: 88,
      featured: false,
    },
    {
      subj: '수학',
      sub: '확률과 통계',
      title: '학업 성취도와 수면시간의 상관관계 데이터 분석',
      desc: '학교 친구들 설문조사 + 통계 검증.',
      diff: '중',
      uniq: 78,
      fit: 84,
      featured: false,
    },
  ],
  예체능: [
    {
      subj: '과학',
      sub: '음악·물리',
      title: '악기별 음색 차이를 푸리에 변환으로 분석',
      desc: '바이올린, 피아노, 기타의 배음 구조를 주파수 분석으로 비교.',
      diff: '상',
      uniq: 92,
      fit: 94,
      featured: true,
    },
    {
      subj: '사회',
      sub: '문화·예술',
      title: 'BTS의 글로벌 성공이 한국 대중음악 산업에 미친 구조적 변화',
      desc: '아이돌 산업의 비즈니스 모델 진화 분석.',
      diff: '중',
      uniq: 82,
      fit: 87,
      featured: false,
    },
    {
      subj: '국어',
      sub: '문학·예술',
      title: '한국 영화의 미장센과 서사구조 분석 (봉준호 작품)',
      desc: '"기생충", "살인의 추억" 등 미장센 요소 비교.',
      diff: '중상',
      uniq: 86,
      fit: 89,
      featured: false,
    },
    {
      subj: '영어',
      sub: '영어 회화',
      title: 'Netflix "Squid Game" 자막 번역에서 본 문화적 의역',
      desc: '한국어→영어 번역 과정에서 손실되는 문화적 뉘앙스.',
      diff: '중',
      uniq: 84,
      fit: 85,
      featured: false,
    },
  ],
};

export const BOOK_DB: Record<Track, BookData> = {
  공학: {
    topword: 'IEEE 2018',
    title: 'Designing<br>the Future',
    author: '— Susskind',
    name: '미래의 직업을 위한 직장이 사라진다',
    meta: '리처드 서스킨드 · 와이즈베리',
    desc: 'AI와 자동화 시대 공학자의 역할을 인공지능 전문가가 분석한 현대의 필독서.',
  },
  자연과학: {
    topword: 'Pulitzer 1998',
    title: 'Guns,<br>Germs,<br>& Steel',
    author: '— Diamond',
    name: '총·균·쇠',
    meta: '재레드 다이아몬드 · 김영사',
    desc: '"국제관계·역사" 키워드와 96% 일치. 자연과학·사회과학 융합 세특에 강력 추천.',
  },
  의약: {
    topword: 'NYT 2010',
    title: 'The<br>Emperor of<br>All Maladies',
    author: '— Mukherjee',
    name: '암: 만병의 황제의 역사',
    meta: '싯다르타 무케르지 · 까치',
    desc: '암 연구 4천 년의 역사를 의사의 시각으로 풀어낸 퓰리처상 수상작.',
  },
  경상: {
    topword: 'NYT 2011',
    title: 'Thinking,<br>Fast and<br>Slow',
    author: '— Kahneman',
    name: '생각에 관한 생각',
    meta: '대니얼 카너먼 · 김영사',
    desc: '노벨경제학상 수상자의 행동경제학 입문서. 시스템1/2 사고의 작동 원리.',
  },
  사회과학: {
    topword: 'NYT 2018',
    title: 'Sapiens',
    author: '— Harari',
    name: '사피엔스',
    meta: '유발 하라리 · 김영사',
    desc: '인지혁명부터 인공지능까지, 인류사를 사회과학의 눈으로 재해석한 필독서.',
  },
  인문: {
    topword: 'Nobel 2017',
    title: 'The<br>Remains of<br>the Day',
    author: '— Ishiguro',
    name: '남아 있는 나날',
    meta: '가즈오 이시구로 · 민음사',
    desc: '노벨문학상 수상자의 대표작. 영국 집사를 통해 본 자아와 시대의 균열.',
  },
  교육: {
    topword: 'NYT 2008',
    title: 'Outliers',
    author: '— Gladwell',
    name: '아웃라이어',
    meta: '말콤 글래드웰 · 김영사',
    desc: '성공의 조건을 사회·심리·교육학 관점에서 분석. 1만 시간의 법칙으로 유명.',
  },
  예체능: {
    topword: 'Pulitzer 1999',
    title: 'Just Kids',
    author: '— Patti Smith',
    name: '저스트 키즈',
    meta: '패티 스미스 · 아트북스',
    desc: '록의 대모와 예술가들의 청춘. 예체능 지망생의 정체성 형성 필독서.',
  },
};

export const MATCH_DB: Record<Track, MatchData[]> = {
  공학: [
    { name: '연세대 화공생명공학', meta: 'A고 · 1.4등급 · 일반전형', score: 87 },
    { name: '고려대 신소재공학', meta: 'B고 · 1.6등급 · 학교추천', score: 82 },
    { name: '서울대 화학생물공학', meta: 'C고 · 1.3등급 · 지역균형', score: 79 },
  ],
  자연과학: [
    { name: '서울대 생명과학부', meta: 'A고 · 1.2등급 · 일반전형', score: 86 },
    { name: '연세대 시스템생물학', meta: 'B고 · 1.5등급 · 활동우수형', score: 81 },
    { name: 'KAIST 생명과학과', meta: 'C고 · 1.4등급 · 학생부종합', score: 78 },
  ],
  의약: [
    { name: '서울대 의예과', meta: 'A고 · 1.0등급 · 지역균형', score: 78 },
    { name: '연세대 의예과', meta: 'B고 · 1.1등급 · 활동우수형', score: 75 },
    { name: '성균관대 의예과', meta: 'C고 · 1.2등급 · 학과모집', score: 72 },
  ],
  경상: [
    { name: '서울대 경영학과', meta: 'A고 · 1.3등급 · 일반전형', score: 84 },
    { name: '연세대 경영학과', meta: 'B고 · 1.5등급 · 활동우수형', score: 80 },
    { name: '고려대 경영학과', meta: 'C고 · 1.6등급 · 학교추천', score: 77 },
  ],
  사회과학: [
    { name: '서울대 정치외교학부', meta: 'A고 · 1.4등급 · 일반전형', score: 85 },
    { name: '연세대 사회학과', meta: 'B고 · 1.6등급 · 활동우수형', score: 81 },
    { name: '고려대 정치외교학과', meta: 'C고 · 1.7등급 · 학교추천', score: 78 },
  ],
  인문: [
    { name: '서울대 국어국문학과', meta: 'A고 · 1.3등급 · 일반전형', score: 86 },
    { name: '연세대 영어영문학과', meta: 'B고 · 1.5등급 · 활동우수형', score: 82 },
    { name: '고려대 철학과', meta: 'C고 · 1.6등급 · 학교추천', score: 79 },
  ],
  교육: [
    { name: '서울대 교육학과', meta: 'A고 · 1.4등급 · 일반전형', score: 84 },
    { name: '서울교대 초등교육과', meta: 'B고 · 1.5등급 · 학교장추천', score: 81 },
    { name: '한국교원대 초등교육과', meta: 'C고 · 1.6등급 · 학생부종합', score: 78 },
  ],
  예체능: [
    { name: '서울대 음악대학', meta: 'A고 · 2.0등급 · 실기우수자', score: 75 },
    { name: '한예종 영상원', meta: 'B고 · 2.5등급 · 학생부종합', score: 72 },
    { name: '연세대 디자인예술학부', meta: 'C고 · 2.0등급 · 활동우수형', score: 70 },
  ],
};

export const UNIVERSITY_DB: Record<Track, University[]> = {
  공학: [
    { name: '한양대 화학공학', major: '서류형 · 인서울 안정', prob: 84, target: false },
    { name: '연세대 화공생명공학', major: '활동우수형 · 인서울 적정', prob: 71, target: true },
    { name: '서울대 화학생물공학', major: '일반전형 · 도전', prob: 38, target: false },
    { name: '성균관대 화학공학', major: '계열모집 · 안정', prob: 91, target: false },
  ],
  자연과학: [
    { name: '연세대 시스템생물학', major: '활동우수형 · 적정', prob: 76, target: true },
    { name: '한양대 생명과학과', major: '서류형 · 안정', prob: 88, target: false },
    { name: '서울대 생명과학부', major: '일반전형 · 도전', prob: 42, target: false },
    { name: 'KAIST 생명과학과', major: '학생부종합 · 적정', prob: 65, target: false },
  ],
  의약: [
    { name: '경희대 한의예과', major: '학생부종합 · 적정', prob: 62, target: true },
    { name: '아주대 의예과', major: 'ACE전형 · 안정', prob: 75, target: false },
    { name: '서울대 의예과', major: '지역균형 · 도전', prob: 28, target: false },
    { name: '성균관대 약학과', major: '학과모집 · 적정', prob: 68, target: false },
  ],
  경상: [
    { name: '연세대 경영학과', major: '활동우수형 · 적정', prob: 72, target: true },
    { name: '한양대 경영학부', major: '서류형 · 안정', prob: 86, target: false },
    { name: '서울대 경영학과', major: '일반전형 · 도전', prob: 35, target: false },
    { name: '성균관대 경영학과', major: '계열모집 · 안정', prob: 89, target: false },
  ],
  사회과학: [
    { name: '연세대 사회학과', major: '활동우수형 · 적정', prob: 73, target: true },
    { name: '한양대 정책학과', major: '서류형 · 안정', prob: 87, target: false },
    { name: '서울대 정치외교학부', major: '일반전형 · 도전', prob: 36, target: false },
    { name: '고려대 행정학과', major: '학교추천 · 안정', prob: 84, target: false },
  ],
  인문: [
    { name: '연세대 영어영문학과', major: '활동우수형 · 적정', prob: 74, target: true },
    { name: '한양대 국어국문학과', major: '서류형 · 안정', prob: 88, target: false },
    { name: '서울대 국어국문학과', major: '일반전형 · 도전', prob: 38, target: false },
    { name: '고려대 한국사학과', major: '학교추천 · 안정', prob: 85, target: false },
  ],
  교육: [
    { name: '한국교원대 초등교육과', major: '학생부종합 · 적정', prob: 72, target: true },
    { name: '경인교대 초등교육과', major: '학교장추천 · 안정', prob: 86, target: false },
    { name: '서울교대 초등교육과', major: '학교장추천 · 적정', prob: 65, target: false },
    { name: '서울대 교육학과', major: '일반전형 · 도전', prob: 38, target: false },
  ],
  예체능: [
    { name: '한국예술종합학교 영상원', major: '실기우수자 · 적정', prob: 68, target: true },
    { name: '연세대 디자인예술학부', major: '활동우수형 · 적정', prob: 72, target: false },
    { name: '서울대 미술대학', major: '실기 · 도전', prob: 35, target: false },
    { name: '홍익대 시각디자인과', major: '실기우수자 · 안정', prob: 82, target: false },
  ],
};

// Initial mission factory based on profile
import type { Mission } from './types';

export function generateInitialMissions(tracks: Track[], hasApiKey: boolean = true): Mission[] {
  const isScience = tracks.some((t) => ['공학', '자연과학', '의약'].includes(t));
  return [
    {
      id: 'm1',
      icon: 'α',
      text: isScience ? '과학 탐구주제 1개 선정하기' : '관심 분야 탐구주제 정하기',
      sub: '추천 5개 대기 중',
      target: 'topic',
      done: false,
    },
    {
      id: 'm2',
      iconClass: 'gold',
      icon: 'β',
      text: '추천 도서 1장 읽고 퀴즈 풀기',
      sub: '약 8분 소요',
      target: 'reading',
      done: false,
    },
    {
      id: 'm3',
      iconClass: 'green',
      icon: 'γ',
      text: '나와 비슷한 합격생 살펴보기',
      sub: '3명 추천 대기',
      target: 'match',
      done: false,
    },
    {
      id: 'm4',
      iconClass: 'blue',
      icon: 'δ',
      text: '제이크 멘토와 첫 대화하기',
      sub: 'AI 멘토 준비됨',
      target: 'chat',
      done: false,
    },
  ];
}
